# Generated by Django 5.0.4 on 2025-10-19 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main_app', '0001_initial'), ('main_app', '0002_product_created_on_product_last_edited_on'), ('main_app', '0003_product_count'), ('main_app', '0004_alter_product_category_alter_product_supplier')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
