# Generated by Django 5.0.4 on 2025-10-19 16:56

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial_squashed_0004_alter_product_category_alter_product_supplier'),
    ]

    operations = [

    ]
