# Generated by Django 5.0.4 on 2025-10-19 17:23
import random

from django.db import migrations
import random
def add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    products = Product.objects.all()
    barcoders = random.sample(range(100000000, 1000000000), len(products))

    for i in range(len(products)):
        p = products[i]
        p.barcode = barcoders[i]
        p.save()

def remove_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    for p in Product.objects.all():
        p.barcode = None
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_product_barcode_alter_product_created_on'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=remove_barcode)
    ]
