# Generated by Django 5.0.4 on 2025-10-21 16:04

from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# main_app.migrations.0003_migrate_unique_brands

class Migration(migrations.Migration):

    replaces = [('main_app', '0001_initial'), ('main_app', '0002_uniquebrands'), ('main_app', '0003_migrate_unique_brands')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniqueBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RunPython(
            code=main_app.migrations.0003_migrate_unique_brands.create_unique_brands,
            reverse_code=main_app.migrations.0003_migrate_unique_brands.reverse_unique_brands_data_creation,
        ),
    ]
