# Generated by Django 5.0.4 on 2025-10-21 15:09

from django.db import migrations

def create_unique_brands(apps, schema_editor):

    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')

    unique_brands = ShoeModel.objects.values_list('brand', flat=True).distinct()

    unique_brands_to_create = [UniqueBrandsModel(brand_name=b) for b in unique_brands]
    UniqueBrandsModel.objects.bulk_create(unique_brands_to_create)

def reverse_unique_brands_data_creation(apps, schema_editor):
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrandsModel.objects.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(code=create_unique_brands, reverse_code=reverse_unique_brands_data_creation)
    ]
