# Generated by Django 5.0.4 on 2025-10-22 15:57

from django.db import migrations


def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    for phone in SmartphoneModel.objects.all():
        phone.price = len(phone.brand) * 120
        phone.save()

def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    for phone in SmartphoneModel.objects.all():
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'
        phone.save()

def set_fields(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_set_fields(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    default_price = SmartphoneModel._meta.get_field('price').get_default()
    default_category = SmartphoneModel._meta.get_field('category').get_default()

    for phone in SmartphoneModel.objects.all():
        phone.price = default_price
        phone.category = default_category
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(code=set_fields, reverse_code=reverse_set_fields),
    ]
