# Generated by Django 5.0.4 on 2025-10-20 18:24
from datetime import timedelta

from django.db import migrations

from main_app.choices import OrderStatusChoices



def set_fields(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')

    for order in OrderModel.objects.all():
        if order.status == OrderStatusChoices.PENDING:
            print("0rder dd", order.order_date)
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == OrderStatusChoices.COMPLETED:
            order.warranty = '24 months'
            order.save()
        elif order.status == OrderStatusChoices.CANCELLED:
            order.delete()


def reverse_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(
            code=set_fields,
            reverse_code=reverse_function,
        )
    ]