# Generated by Django 5.0.4 on 2025-11-24 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_quest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='code',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z#]{4}$')]),
        ),
    ]
